#pragma once

using namespace ATL;

template <class T>
class CProxy_INativeExtensionsEvents : public IConnectionPointImpl<T, &__uuidof( _INativeExtensionsEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
