#pragma once

using namespace ATL;

template <class T>
class CProxy_INativeMessagingEvents : public IConnectionPointImpl<T, &__uuidof( _INativeMessagingEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
