#pragma once

using namespace ATL;

template <class T>
class CProxy_INativeBackgroundEvents : public IConnectionPointImpl<T, &__uuidof( _INativeBackgroundEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
