// Forge.idl : IDL source for Forge
//

// This file will be processed by the MIDL tool to
// produce the type library (Forge.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

#include "vendor.h"


// INativeBackground
[
    object,
    uuid(VENDOR_UUID_INativeBackground),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface INativeBackground : IDispatch {
    [id(1)]  HRESULT load    ([in] BSTR uuid, [in] BSTR url, [in] BOOL isVisible,
                              [out,retval] unsigned int *instanceId);
    [id(2)]  HRESULT unload  ([in] BSTR uuid, [in] unsigned int instanceId);
    [id(3)]  HRESULT visible ([in] BSTR uuid, [in] BOOL isVisible);
};


// INativeExtensions
[
    object,
    uuid(VENDOR_UUID_INativeExtensions),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface INativeExtensions : IDispatch {
    [id(1)]  HRESULT log         ([in] BSTR uuid, [in] BSTR message);
    [id(2)]  HRESULT prefs_get   ([in] BSTR uuid, [in] BSTR name, 
                                  [in] IDispatch *success, 
                                  [in] IDispatch *error);
    [id(3)]  HRESULT prefs_set   ([in] BSTR uuid, [in] BSTR name, [in] BSTR value, 
                                  [in] IDispatch *success, 
                                  [in] IDispatch *error);
    [id(4)]  HRESULT prefs_keys  ([in] BSTR uuid, 
                                  [in] IDispatch *success, 
                                  [in] IDispatch *error);
    [id(5)]  HRESULT prefs_all   ([in] BSTR uuid, 
                                  [in] IDispatch *success, 
                                  [in] IDispatch *error);
    [id(6)]  HRESULT prefs_clear ([in] BSTR uuid, [in] BSTR name,
                                  [in] IDispatch *success, 
                                  [in] IDispatch *error);
    [id(7)]  HRESULT getURL      ([in] BSTR url, 
                                  [out,retval] BSTR *out_url);
    [id(8)]  HRESULT xhr         ([in] BSTR method, 
                                  [in] BSTR url, 
                                  [in] BSTR data, 
                                  [in] BSTR contentType,
                                  [in] BSTR headers,
                                  [in] IDispatch *success,
                                  [in] IDispatch *error);
    [id(9)]  HRESULT notification ([in] BSTR icon, [in] BSTR title, [in] BSTR text,
                                   [out,retval] BOOL *out_success);
    [id(10)] HRESULT set_tabId    ([in] UINT tabId);
    [id(11)] HRESULT get_tabId    ([out,retval] UINT *out_tabId);
    [id(12)] HRESULT set_location ([in] BSTR location);
    [id(13)] HRESULT get_location ([out,retval] BSTR *out_location);
    [id(14)] HRESULT cookies_get  ([in] BSTR url, [in] BSTR name,
                                   [in] IDispatch *success, [in] IDispatch *error);
    [id(15)] HRESULT cookies_remove ([in] BSTR url, [in] BSTR name,
                                     [out, retval] BOOL *out_success);

};


// INativeMessaging
[
    object,
    uuid(VENDOR_UUID_INativeMessaging),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface INativeMessaging : IDispatch {
    [id(1)]  HRESULT load         ([in] BSTR uuid, 
                                   [in] unsigned int instanceId);
    [id(2)]  HRESULT unload       ([in] BSTR uuid, 
                                   [in] unsigned int instanceId);
    [id(3)]  HRESULT tabs_set     ([in] BSTR uuid, 
                                   [in] UINT tabId,
                                   [in] BSTR url,
                                   [in] BSTR title,
                                   [in] BOOL focused);
    [id(4)]  HRESULT tabs_active  ([in] BSTR uuid, 
                                   [in] IDispatch *callback,
                                   [out,retval] UINT *out_tabId);
    [id(5)]  HRESULT fg_listen    ([in] BSTR uuid, [in] UINT tabId, 
                                   [in] BSTR type,
                                   [in] IDispatch *callback,
                                   [in] IDispatch * error);
    [id(6)]  HRESULT fg_broadcast ([in] BSTR uuid, 
                                   [in] BSTR type,
                                   [in] BSTR content,
                                   [in] IDispatch *callback,
                                   [in] IDispatch *error);
    [id(7)]  HRESULT fg_toFocussed([in] BSTR uuid, 
                                   [in] BSTR type,
                                   [in] BSTR content,
                                   [in] IDispatch *callback,
                                   [in] IDispatch *error);
    [id(8)]  HRESULT fg_broadcastBackground([in] BSTR uuid,
                                            [in] BSTR type,
                                            [in] BSTR content,
                                            [in] IDispatch *callback,
                                            [in] IDispatch *error);
    [id(9)] HRESULT bg_listen     ([in] BSTR uuid, 
                                   [in] BSTR type,
                                   [in] IDispatch *callback,
                                   [in] IDispatch *error);
    [id(10)] HRESULT bg_broadcast ([in] BSTR uuid,
                                   [in] BSTR type,
                                   [in] BSTR content,
                                   [in] IDispatch *callback,
                                   [in] IDispatch *error);
    [id(11)] HRESULT bg_toFocussed([in] BSTR uuid,
                                   [in] BSTR type,
                                   [in] BSTR content,
                                   [in] IDispatch *callback,
                                   [in] IDispatch *error);

};


// INativeControls
[
    object,
    uuid(VENDOR_UUID_INativeControls),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface INativeControls : IDispatch {
    [id(1)]  HRESULT load             ([in] BSTR uuid, 
                                       [in] BSTR extensionPath,
                                       [in] unsigned int instanceId,
                                       [in] ULONG hwnd);
    [id(2)]  HRESULT unload           ([in] BSTR uuid, 
                                       [in] unsigned int instanceId);
    [id(3)]  HRESULT popup_visible    ([in] BSTR  uuid, 
                                       [in] BOOL  isVisible,
                                       [in] POINT point); // @ugly
    [id(4)]  HRESULT button_setIcon   ([in] BSTR uuid, 
                                       [in] BSTR url,
                                       [in] IDispatch *success, 
                                       [in] IDispatch *error); 
    [id(5)]  HRESULT button_setURL    ([in] BSTR uuid, 
                                       [in] BSTR url,
                                       [in] IDispatch *success, 
                                       [in] IDispatch *error);
    [id(6)]  HRESULT button_onClicked ([in] BSTR uuid, 
                                       [in] IDispatch *callback);
    [id(7)]  HRESULT button_click     ([in] BSTR uuid, 
                                       [in] POINT point); // @ugly
    [id(8)]  HRESULT button_setTitle  ([in] BSTR uuid, 
                                       [in] BSTR title,
                                       [in] IDispatch *success, 
                                       [in] IDispatch *error);
    [id(9)]  HRESULT button_setBadge  ([in] BSTR uuid, 
                                       [in] INT number,
                                       [in] IDispatch *success, 
                                       [in] IDispatch *error);
    [id(10)] HRESULT button_setBadgeBackgroundColor ([in] BSTR uuid, 
                                                     [in] BYTE r, 
                                                     [in] BYTE g, 
                                                     [in] BYTE b,
                                                     [in] BYTE a,
                                                     [in] IDispatch *success,
                                                     [in] IDispatch *error);

    [id(11)] HRESULT popup_hwnd([in]         BSTR  uuid, 
                                [out]        BOOL  *out_visible,
                                [out,retval] ULONG *out_hwnd);
};


// ForgeLib
[
    uuid(VENDOR_UUID_ForgeLib),
    version(1.0),
]
library ForgeLib
{
    importlib("stdole2.tlb");

    // _INativeBackgroundEvents
    [
     uuid(VENDOR_UUID__INativeBackgroundEvents)
    ]
    dispinterface _INativeBackgroundEvents
    {
        properties:
        methods:
    };

    // NativeBackground
    [
        uuid(VENDOR_UUID_NativeBackground)
    ]
    coclass NativeBackground
    {
        [default] interface INativeBackground;
        [default, source] dispinterface _INativeBackgroundEvents;
    };

    // _INativeExtensionsEvents
    [
        uuid(VENDOR_UUID__INativeExtensionsEvents)
    ]
    dispinterface _INativeExtensionsEvents
    {
        properties:
        methods:
    };

    // NativeExtensions
    [
        uuid(VENDOR_UUID_NativeExtensions)
    ]
    coclass NativeExtensions
    {
        [default] interface INativeExtensions;
        [default, source] dispinterface _INativeExtensionsEvents;
    };

    // _INativeMessagingEvents
    [
     uuid(VENDOR_UUID__INativeMessagingEvents)
    ]
    dispinterface _INativeMessagingEvents
    {
        properties:
        methods:
    };

    // NativeMessaging
    [
        uuid(VENDOR_UUID_NativeMessaging)
    ]
    coclass NativeMessaging
    {
        [default] interface INativeMessaging;
        [default, source] dispinterface _INativeMessagingEvents;
    };

    // NativeControls
    [
        uuid(VENDOR_UUID_NativeControls)
    ]
    coclass NativeControls
    {
        [default] interface INativeControls;
    };
};


