import "oaidl.idl";
import "ocidl.idl";

#include "vendor.h"


/**
 * Interface: IBrowserHelperObject 
 */
[
    object,
    uuid(VENDOR_UUID_IBrowserHelperObject),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface IBrowserHelperObject : IDispatch {
};


/** 
 * Library: ForgeBHOLib */
[
    uuid(VENDOR_UUID_ForgeBHOLib),
    version(1.0),
]
library ForgeBHOLib {
    importlib("stdole2.tlb");
    importlib("Forge.tlb");

    [
        uuid(VENDOR_UUID_BrowserHelperObject)
    ]
    coclass BrowserHelperObject {
        [default] interface IBrowserHelperObject;
    };
};
